name: cart_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  google_sign_in:
  firebase_core:
  firebase_auth:
  get_storage: ^2.1.1
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/